### ISSUE TITLE
Scripts issolation does not work

### ISSUE THREAD

**Issue by NikolayPianikov** [chechulnikov/eucalypt#8]
Одно из главных требований была безопасность выполнения и изоляция. Но при переиспользовании контейнеров через "pool" изоляции нет, и злономеренный скрипт может оставить процесс в памяти контейнера. Мы моглибы не использовать контейнеры, а просто запускать срипт под неким ограниченным ползователем прямо на хосте.

**Comment by chechulnikov** [comment]
> Но при переиспользовании контейнеров через "pool" изоляции нет, и злономеренный скрипт может оставить процесс в памяти контейнера

1. После каждого исполнения контейнер асинхронно [ре-ранится](https://github.com/chechulnikov/eucalypt/blob/main/src/src/main/kotlin/eucalypt/business/executing/executors/BaseExecutor.kt#L73) с тем же именем. То есть убивается и запускается. Пока он в состояниях RELEASED или RESET, пул не отдаёт его пользователю. Контейнер становится доступен только в состоянии READY.
2. Запущенный таким образом процесс будет запущен в контейнере под [ограниченным](https://github.com/chechulnikov/eucalypt/blob/main/src/src/images/dotnet6/dockerfile#L14) [пользователем](https://github.com/chechulnikov/eucalypt/blob/main/src/src/main/kotlin/eucalypt/business/executing/executors/DotnetExecutor.kt#L21), который может только съесть все отпущенные контейнеру ресурсы и всё.
3. Даже если контейнер подвиснет, пока пул крутится в памяти, он [мониторит](https://github.com/chechulnikov/eucalypt/blob/main/src/src/main/kotlin/eucalypt/business/executing/pool/ExecutorsPoolImpl.kt#L140) подвисшие контейнеры и убивает их по отдельному таймауту.
4. Если даже пул умер, то после его перезапуска он соберёт "мусор" – контейнеры, которые были запущены ранее просто удалятся.


> Мы моглибы не использовать контейнеры, а просто запускать срипт под неким ограниченным ползователем прямо на хосте.

Разница в удобстве. Контейнер – это всего лишь cgroup На мой взгляд, контейнер значительно удобнее, т.к. даёт и возможности и тулинг из коробки c удобным API. И большим количеством уже продуманных кейсов.

@NikolayPianikov , вероятно я не понял твой поинт. Можешь привести пример кейса, когда это не сработает?

**Comment by NikolayPianikov** [comment]
Да, я пропустил код с ресетом executor так как предполагал что это ответвенность пула а наша здача просто вернуть его пулу а ExecutorsPool не содержит API для этого

**Comment by NikolayPianikov** [comment]
#11 created
